<?php

namespace Tests\Browser;

use App\Transaction;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Browser\Pages\HomePage;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class CFA15Test extends DuskTestCase
{

    use DatabaseMigrations;
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->runDatabaseMigrations();

    }


    /**
     * A Dusk test example.
     *
     * @return void
     * @throws \Exception
     * @throws \Throwable
     */
    public function testCFA15()
    {
        $this->browse(function (Browser $browser) {

            $user = factory(User::class)->create();

            $t = factory(Transaction::class)->make([
                'user_id' => $user->id,
                'amount' => '!invalid'
            ]);



            $browser
                ->loginAs($user)
                ->visit(new HomePage())
                ->openNewTransactionModal()
                ->inputTransaction($t)
                ->attemptSaveTransaction()
                ->waitFor('@feedback-invalid-amount')


            ;
        });
    }
}
