<?php

namespace Tests\Browser;



use Laravel\Dusk\Browser;
use Tests\Browser\Components\NavigationBar;
use Tests\Browser\Pages\HomePage;
use Tests\Browser\Pages\WelcomePage;
use Tests\CashFlowAppUserLoggedInTestCase;


class HomePageTest extends CashFlowAppUserLoggedInTestCase
{



    /**
     * @throws \Exception
     * @throws \Throwable
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->browse(function (Browser $browser) {
            $browser
                ->visit(new HomePage());
        });

    }

    /**
     * @return void
     * @throws \Exception
     * @throws \Throwable
     */
    public function testUserSeeApplicationName() {

        $this->browse(function (Browser $browser) {

            $browser
                ->within(new NavigationBar(), function (Browser $browser) {
                    $browser->assertSeeIn('@text-app-name', env('APP_NAME'));
            });

        });
    }

    /**
     * @return void
     * @throws \Exception
     * @throws \Throwable
     */
    public function testUserSeesHisLogin() {

        $this->browse(function (Browser $browser) {
            // TODO: Change autogenerated stub

            $browser
                ->within(new NavigationBar(), function (Browser $browser){
                   $browser->assertSeeIn('@nav-profile-links', $this->currentUser->name);
                });

        });


    }

    /**
     * @return void
     * @throws \Exception
     * @throws \Throwable
     */
    public function testUserSeesLogoutLink() {

        $this->browse(function (Browser $browser) {

            // TODO: Change autogenerated stub

            $browser->within(new NavigationBar(), function(Browser $browser){

                $browser
                    ->openProfileDropDown()
                    ->assertSeeLink('Logout')
                    ;
            });

        });


    }

    /**
     * @return void
     * @throws \Exception
     * @throws \Throwable
     */
    public function testUserCanLogout() {

        $this->browse(function (Browser $browser) {

            $browser
                ->within(new NavigationBar(), function (Browser $browser){

                    $browser->openProfileDropDown();
                    $browser->clickLink('Logout');
                    $browser->on(new WelcomePage());

                })
                ->assertSee(env('APP_NAME')) //some log out message//
                ;
        });


    }


}
