sudo: required
language: php

php:
  - 7.1

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.travis .env
  - composer install --no-interaction
  - mysql -e 'create database homestead_test;'
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit