sudo: required
language: php
dist: trusty

php:
  - 7.2

addons:
   chrome: stable

services:
  - mysql

before_script:
    - cp .env.travis .env
  - composer install --no-interaction
  - mysql -e 'create database homestead_test;'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1:8000 &
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - php artisan passport:install
  - php artisan serve &


script:
  - php artisan dusk

after_script:
  - cat storage/logs/laravel.log
 # - vendor/bin/phpunit
