sudo: required
language: php
dist: trusty

php:
  - 7.1

services:
  - mysql

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - mysql -e 'create database homestead_test;'
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - php artisan passport:install


script:

  - vendor/bin/phpunit
