sudo: required
language: php
dist: trusty

php:
  - 7.1

addons:
    chrome: stable

cache:
  directories:
    - "node_modules"

services:
  - mysql

before_script:

  - cp .env.travis .env
  - composer install --no-interaction
  - npm install
  - npm run production
  - mysql -e 'create database homestead_test;'
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - php artisan passport:install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve > /dev/null 2>&1 &



script:

  - php artisan dusk
  - vendor/bin/phpunit
