sudo: required
language: php

php:
  - 7.1

addons:
   chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.travis .env
  - composer install --no-interaction
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - npm run production
  - mysql -e 'create database homestead_test;'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &
  - php artisan key:generate
  - php artisan migrate
  - php artisan serve &


script:
  - php artisan dusk

after_script:
  - cat storage/logs/laravel.log
 # - vendor/bin/phpunit
