<?php

namespace Tests\Feature;

use App\Transaction;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use TestDataSeeder;
use Tests\TestCase;

class TransactionApiTest extends TestCase
{

    use DatabaseMigrations;
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(TestDataSeeder::class);
    }

    public function testTransactionWithGuard() {

        $intRandomNoOfTransactions = rand(10,20);

        // we have one and only user now
        factory(Transaction::class, $intRandomNoOfTransactions)->create(['user_id' => 1]);

        // make a call
        $response = $this->json('GET', '/api/transaction');

        // check response
        $response->assertStatus(200);
        $response->assertJsonCount($intRandomNoOfTransactions, 'data');


    }

    public function testGetSingleTransaction() {


        $transaction = factory(Transaction::class, 1) ->create(['user_id' => 1])->first();
        $id = $transaction->id;

        $response = $this->json('GET', '/api/transaction/'.$id);


        $response->assertStatus(200);


        //TODO: add other fields to test
        $response->assertJson(['data' => [
            'id' => $id,
            'amount' => $transaction->amount
        ]]);




    }

    public function testPostSimpleTransaction() {

        $transaction = factory(Transaction::class, 1)->make(['user_id' => 1])->first();

        $response = $this->json('POST', '/api/transaction', ['transaction' => $transaction]);

        $response->assertStatus(200);

    }

    public function testPostTransactionValidation() {

        $response = $this->json('POST', '/api/transaction', []); // send empty request

        $response->assertStatus(422); // expect validation errors

        $response->assertJsonValidationErrors(['transaction']);


    }
}
