<?php

namespace App;

use App\Scopes\CurrentUserScope;
use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
    //

    protected $fillable = [
        'description',
        'amount',
        'varying',
        'planned_on',
        'actual_on',
        'user_id'
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new CurrentUserScope());
    }

    /**
     * Scope a query to only include users of a given type.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param \DateTime $from
     * @param \DateTime $to
     * @return void
     */
    public function scopeBetween($query, $from, $to) {

        $query->whereBetween('planned_on', [$from, $to]);

    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeOrdered($query) {

        $query->orderBy('planned_on', 'ASC');

    }
}
